name: ros2_jazzy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  jazzy:
    name: ros2-jazzy
    uses: ./.github/workflows/ros2_template.yml
    with:
      docker_base_image: rostooling/setup-ros-docker:ubuntu-noble-latest
      ros_distro: jazzy
